package CInterface;

/**
* CInterface/FlightServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Umer-PC/workspace-tempDemo/FlightServer_Corba/src/CInterface.idl
* Saturday, November 5, 2016 8:12:54 PM EDT
*/

public final class FlightServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public CInterface.FlightServerInterface value = null;

  public FlightServerInterfaceHolder ()
  {
  }

  public FlightServerInterfaceHolder (CInterface.FlightServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CInterface.FlightServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CInterface.FlightServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CInterface.FlightServerInterfaceHelper.type ();
  }

}
