package CInterface;


/**
* CInterface/FlightServerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Umer-PC/workspace-tempDemo/FlightServer_Corba/src/CInterface.idl
* Saturday, November 5, 2016 8:12:54 PM EDT
*/

public abstract class FlightServerInterfacePOA extends org.omg.PortableServer.Servant
 implements CInterface.FlightServerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CInterface/FlightServerInterface/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phoneNumber = in.read_string ();
         String destination = in.read_string ();
         String deptDate = in.read_string ();
         String flightType = in.read_string ();
         String $result = null;
         $result = this.bookFlight (firstName, lastName, address, phoneNumber, destination, deptDate, flightType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CInterface/FlightServerInterface/getBookedFlightCount
       {
         String managerId = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CInterface/FlightServerInterface/editFlightRecord
       {
         String recordId = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editFlightRecord (recordId, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CInterface/FlightServerInterface/transferReservation
       {
         String passengerID = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (passengerID, currentCity, otherCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CInterface/FlightServerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightServerInterface _this() 
  {
    return FlightServerInterfaceHelper.narrow(
    super._this_object());
  }

  public FlightServerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return FlightServerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class FlightServerInterfacePOA
