package CInterface;


/**
* CInterface/FlightServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Umer-PC/workspace-tempDemo/FlightServer_Corba/src/CInterface.idl
* Saturday, November 5, 2016 8:12:54 PM EDT
*/

public interface FlightServerInterfaceOperations 
{
  String bookFlight (String firstName, String lastName, String address, String phoneNumber, String destination, String deptDate, String flightType);
  String getBookedFlightCount (String managerId);
  String editFlightRecord (String recordId, String fieldName, String newValue);
  String transferReservation (String passengerID, String currentCity, String otherCity);
} // interface FlightServerInterfaceOperations
