package CInterface;


/**
* CInterface/FlightServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Umer-PC/workspace-tempDemo/FlightServer_Corba/src/CInterface.idl
* Saturday, November 5, 2016 8:12:54 PM EDT
*/

abstract public class FlightServerInterfaceHelper
{
  private static String  _id = "IDL:CInterface/FlightServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, CInterface.FlightServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CInterface.FlightServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CInterface.FlightServerInterfaceHelper.id (), "FlightServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CInterface.FlightServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlightServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CInterface.FlightServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CInterface.FlightServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CInterface.FlightServerInterface)
      return (CInterface.FlightServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CInterface._FlightServerInterfaceStub stub = new CInterface._FlightServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CInterface.FlightServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CInterface.FlightServerInterface)
      return (CInterface.FlightServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CInterface._FlightServerInterfaceStub stub = new CInterface._FlightServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
